[[pages]]
path = "Welcome.py"
name = "Welcome"
icon = "ğŸ¡"

[[pages]]
name = "Datasets â†“"
icon = ""
is_section = true

[[pages]]
path ="pages/mind2web.py"
name = "Mind2Web"
icon = "ğŸ§ "

[[pages]]
path = "pages/webarena.py"
name = "WebArena"
icon = "ğŸŸ"

[[pages]]
path = "pages/agent_instruct.py"
name = "AgentInstruct"
icon = "ğŸ‘¾"

[[pages]]
name = "Tools â†“"
icon = ""
is_section = true

[[pages]]
path = "pages/treevoyager.py"
name = "TreeVoyager (DOM Parser)"
icon = "ğŸŒ³"